spring.application.name=ModPla

# Configure the database
spring.datasource.url=jdbc:mariadb://localhost:3306/modpla
spring.datasource.username=user_name
spring.datasource.password=password
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configure JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Configure Gemini API
gemini.api.key=your_genai_api_key